name: newyorktimes_app
description: App de notícias.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  #Permite colocar de forma facilitada o icone do launcher do app
  flutter_launcher_icons: ^0.8.1
  #Permite colocar de forma facilitada o nome do launcher do app
  flutter_launcher_name: ^0.0.1
  #BottomNavigator Utilizado
  bottom_navy_bar: ^5.5.0
  #Repositório de fonts
  font_awesome_flutter: ^8.8.1
  ##Firebase
  #Realiza  a conexão do app com o firebase de forma facilitada
  firebase_core: ^0.5.0
  #Permite acessar e usar métodos dos cloudfirestore
  cloud_firestore: ^0.14.1+2
  #Permite realizar operações de autenticação no firebase - Cadastro, logins etc
  firebase_auth: ^0.18.1+1
  ####
  #Permite usar um placeholder de transparência, para ser utilizado no FadeIn em algumas situações no app
  transparent_image: ^1.0.0
  #Permite criarmos uma grid de elementos com dimensões diferentes
  flutter_staggered_grid_view: ^0.3.2
  #Permite guardar os estados da aplicação, nesse caso foi utilizado para realizar operações de auth e as operações do crud. Usado tbm para verificar se está carregando e se o usuário está logado.
  scoped_model: ^1.0.1
  #Permite criar carrosseis de forma facilitada
  carousel_pro: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


#Adiciona-se o icone no launcher
flutter_icons:
  android: true
  ios: true
  image_path: "logo_simplificado220x225.png"

#Adiciona-se um nome no launcher
flutter_launcher_name:
  name: "NYTimes"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  #Três imagens usadas no app
  assets:
    - config_app/imagens/logo_fundo_preto_letra_branca.png
    - config_app/imagens/logo_simplificado.png
    - config_app/imagens/logo_simplificado_branco.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  #Importamos as fonts
  fonts:
    - family: Piazzolla
      fonts:
        - asset: config_app/fontes/Piazzolla/static/Piazzolla-Black-opsz=8.ttf
          weight: 400
        - asset: config_app/fontes/Piazzolla/static/Piazzolla-Black-opsz=9.ttf
          weight: 500
        - asset: config_app/fontes/Piazzolla/static/Piazzolla-Black-opsz=10.ttf
          weight: 600
        - asset: config_app/fontes/Piazzolla/static/Piazzolla-Bold-opsz=18.ttf
          weight: 700
        - asset: config_app/fontes/Piazzolla/static/Piazzolla-ExtraBold-opsz=28.ttf
          weight: 900
